drop table if exists comments;
drop table if exists bookings;
drop table if exists items;
drop table if exists requests;
drop table if exists users;

CREATE TABLE IF NOT EXISTS users
(
    id bigint generated by default as identity not null primary key
    , name varchar(255) NOT NULL
    , email varchar(512) NOT NULL
    , constraint UQ_USER_EMAIL unique (email)
);
create table if not exists requests
(
    id bigint generated by default as identity not null primary key
    , description varchar(1024) not null
    , user_id bigint not null
    , created DateTime not null
    , foreign key (user_id) references users(id) on delete cascade
);
create table if not exists items
(
    id bigint generated by default as identity not null primary key
    , name varchar(255) not null
    , description varchar(512) not null
    , available bool not null default true
    , owner_id bigint not null
    , request_id bigint null
    , foreign key (owner_id) references users(id) on delete cascade
    , foreign key (request_id) references requests(id)
);
create type if not exists booking_status as enum('WAITING', 'APPROVED', 'REJECTED');
create table if not exists bookings
(
    id bigint generated by default as identity not null primary key
    , item_id bigint not null
    , pb datetime not null
    , pe datetime not null
    , status booking_status not null default 'WAITING'
    , user_id bigint not null
    , foreign key (item_id) references items(id) on delete cascade
    , foreign key (user_id) references users(id) on delete cascade
);
create table if not exists comments
(
    id bigint generated by default as identity not null primary key
    , item_id bigint not null
    , user_id bigint not null
    , comment varchar(1024) not null
    , created DateTime not null
    , foreign key (item_id) references items(id) on delete cascade
    , foreign key (user_id) references users(id) on delete cascade
);